module.exports = {
  title: "Descriptive statistics",
  track: 'stats', tool: 'Both', level: 'beginner', time: "~4-5 hrs",
  lede: "Before any fancy model, you describe what you have. Descriptive statistics summarise a dataset’s centre, spread and shape — and knowing which summary to trust (and which lies) is a genuine skill. This comprehensive lesson works through AQI distributions, temperature profiles, and census-tract comparisons in Python and R.",
  learn: [
    "Summarise centre: mean vs. median vs. mode",
    "Measure spread: range, IQR, standard deviation",
    "Read distributions and spot skew with histograms and boxplots",
    "Detect and reason about outliers",
    "Group and compare environmental data by station, season, or tract",
    "Interpret correlation (and its limits)"
  ],
  prereqs: [{"id":"pandas","label":"pandas"}],
  resources: [
    {
      "name": "Khan Academy: statistics",
      "url": "https://www.khanacademy.org/math/statistics-probability",
      "kind": "course"
    },
    {
      "name": "Seeing Theory (visual stats)",
      "url": "https://seeing-theory.brown.edu/",
      "kind": "interactive"
    },
    {
      "name": "pandas describe()",
      "url": "https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html",
      "kind": "docs"
    }
  ],
  unlock: {"label":"Western heat waves","url":"projects.html","blurb":"Summarise temperature distributions and quantify how extreme a heat wave really is."},
  content: [
    { type: "p", html: "Environmental datasets are rarely tidy single numbers. An air-quality file might hold hourly AQI from dozens of stations; a census tract table lists median income and diesel burden for thousands of polygons. <strong>Descriptive statistics</strong> summarise centre, spread, and shape before any model. This lesson uses AQI, temperature, and tract data in Python and R." },
    { type: "callout", html: "Python examples use pandas; R examples use dplyr and base stats. You do not need both languages — seeing the same idea twice builds intuition.", variant: "note", title: "How to use this lesson." },
    { type: "h2", text: "The three questions" },
    { type: "p", html: "For any numeric column: where is the <strong>centre</strong>, how <strong>spread out</strong> are values, and what <strong>shape</strong> does the distribution have?" },
    { type: "list", items: ["<strong>Centre:</strong> mean, median, mode","<strong>Spread:</strong> range, IQR, standard deviation","<strong>Shape:</strong> symmetric, skewed, bimodal"] },
    { type: "callout", html: "A histogram takes seconds and prevents reporting a mean when wildfire days dominate the average.", variant: "tip", title: "Plot first, summarise second." },
    { type: "h2", text: "Loading environmental data" },
    { type: "code", lang: "python", code: "import pandas as pd\naqi = pd.read_csv(\"la_aqi_hourly.csv\", parse_dates=[\"timestamp\"])\ntemp = pd.read_csv(\"western_daily_temp.csv\", parse_dates=[\"date\"])\ntracts = pd.read_csv(\"la_tracts_env.csv\")" },
    { type: "code", lang: "r", code: "library(readr)\nlibrary(dplyr)\naqi <- read_csv(\"la_aqi_hourly.csv\")\ntemp <- read_csv(\"western_daily_temp.csv\")\ntracts <- read_csv(\"la_tracts_env.csv\")" },
    { type: "p", html: "Notice different grains: AQI is hourly per station; temperature is daily; tracts are one row per polygon. The right summary depends on the grain." },
    { type: "h2", text: "One-line summaries" },
    { type: "h3", text: "Python: describe()" },
    { type: "code", lang: "python", code: "aqi[\"aqi\"].describe()" },
    { type: "h3", text: "R: summary()" },
    { type: "code", lang: "r", code: "summary(aqi$aqi)" },
    { type: "table", head: ["Statistic","Meaning","Robust?"], rows: [["Mean","Arithmetic average","No"],["Median","Middle value","Yes"],["Std dev","Typical distance from mean","No"],["IQR","Spread of middle 50%","Yes"]] },
    { type: "h2", text: "Centre: mean vs median" },
    { type: "p", html: "The mean is the sum divided by count; the median is the middle sorted value. They agree for symmetric data but diverge when skewed." },
    { type: "code", lang: "python", code: "print(\"mean:\", aqi[\"aqi\"].mean())\nprint(\"median:\", aqi[\"aqi\"].median())\nprint(\"gap:\", aqi[\"aqi\"].mean() - aqi[\"aqi\"].median())" },
    { type: "code", lang: "r", code: "mean(aqi$aqi, na.rm = TRUE)\nmedian(aqi$aqi, na.rm = TRUE)" },
    { type: "callout", html: "One wildfire day at AQI 300 raises the monthly mean while the median barely moves. For skewed pollution data, lead with the <strong>median</strong> as typical.", variant: "warn", title: "The mean is fragile." },
    { type: "h3", text: "Mode for categories" },
    { type: "code", lang: "python", code: "aqi[\"station_id\"].value_counts().head()" },
    { type: "code", lang: "r", code: "sort(table(aqi$station_id), decreasing = TRUE)[1:5]" },
    { type: "h2", text: "Grouping by station or tract" },
    { type: "p", html: "A global mean hides geography. Group first — mean AQI per station, median diesel burden per district." },
    { type: "code", lang: "python", code: "by_station = aqi.groupby(\"station_id\")[\"aqi\"].agg([\"count\",\"mean\",\"median\",\"std\"])\nby_station.sort_values(\"mean\", ascending=False).head(10)" },
    { type: "code", lang: "r", code: "aqi %>% group_by(station_id) %>%\n  summarise(n=n(), mean_aqi=mean(aqi, na.rm=TRUE),\n            median_aqi=median(aqi, na.rm=TRUE)) %>%\n  arrange(desc(mean_aqi))" },
    { type: "h2", text: "Spread measures" },
    { type: "code", lang: "python", code: "s = aqi[\"aqi\"]\nq1, q3 = s.quantile([0.25, 0.75])\niqr = q3 - q1\nprint(\"range:\", s.max()-s.min(), \"IQR:\", iqr, \"std:\", s.std())" },
    { type: "code", lang: "r", code: "IQR(aqi$aqi)\nsd(aqi$aqi, na.rm=TRUE)" },
    { type: "p", html: "Standard deviation is in the same units as the data — typical distance from the mean. IQR describes the middle half and resists outliers." },
    { type: "h2", text: "Boxplots for comparison" },
    { type: "code", lang: "python", code: "import matplotlib.pyplot as plt\naqi.boxplot(column=\"aqi\", by=\"season\", figsize=(8,4))\nplt.suptitle(\"\"); plt.title(\"AQI by season\")" },
    { type: "code", lang: "r", code: "library(ggplot2)\nggplot(aqi, aes(x=season, y=aqi)) + geom_boxplot()" },
    { type: "callout", html: "Points beyond 1.5 times IQR are flagged — a visual convention, not a command to delete data.", variant: "note", title: "Boxplot whiskers." },
    { type: "h2", text: "Shape: histograms" },
    { type: "code", lang: "python", code: "aqi[\"aqi\"].plot(kind=\"hist\", bins=40, edgecolor=\"white\")" },
    { type: "list", items: ["<strong>Right-skewed:</strong> long tail of high values; mean &gt; median — common for AQI.","<strong>Symmetric:</strong> mean approximates median.","<strong>Bimodal:</strong> two humps — two regimes (weekday vs weekend, dry vs wet)."] },
    { type: "h2", text: "Temperature distributions" },
    { type: "code", lang: "python", code: "summer = temp[temp[\"month\"].isin([6,7,8])]\nwinter = temp[temp[\"month\"].isin([12,1,2])]\nprint(\"summer median:\", summer[\"tmax_c\"].median())\nprint(\"winter median:\", winter[\"tmax_c\"].median())" },
    { type: "code", lang: "python", code: "temp.groupby(\"month\")[\"tmax_c\"].agg([\"mean\",\"median\",\"std\"])" },
    { type: "callout", html: "Confirm Celsius vs Fahrenheit at load time and document column names (tmax_c).", variant: "note", title: "Units matter." },
    { type: "h2", text: "Percentiles" },
    { type: "p", html: "The 90th percentile of daily AQI is exceeded only 10% of the time — a natural bad-air threshold." },
    { type: "code", lang: "python", code: "aqi[\"aqi\"].quantile([0.5, 0.9, 0.95, 0.99])" },
    { type: "code", lang: "r", code: "quantile(aqi$aqi, c(0.5, 0.9, 0.95, 0.99), na.rm=TRUE)" },
    { type: "h2", text: "Outliers: detect, do not delete" },
    { type: "code", lang: "python", code: "q1, q3 = aqi[\"aqi\"].quantile([0.25, 0.75])\niqr = q3 - q1\nlow, high = q1 - 1.5*iqr, q3 + 1.5*iqr\noutliers = aqi[(aqi[\"aqi\"] < low) | (aqi[\"aqi\"] > high)]\nprint(len(outliers), \"flagged hours\")" },
    { type: "steps", items: ["Plot the column — is the outlier isolated or part of a cluster?","Check metadata — sensor error or unit mismatch?","Cross-reference events — wildfire, inversion layer?","Decide: keep, cap, or exclude with documentation."] },
    { type: "callout", html: "In environmental data, the outlier is often the whole point — the heat wave or smoke event. Investigate before removing.", variant: "warn", title: "Do not auto-delete." },
    { type: "h2", text: "Z-scores" },
    { type: "p", html: "z = (x - mean) / std measures standardised distance from centre. Useful for comparing extremes across variables." },
    { type: "code", lang: "python", code: "aqi[\"z\"] = (aqi[\"aqi\"] - aqi[\"aqi\"].mean()) / aqi[\"aqi\"].std()\naqi[aqi[\"z\"].abs() > 3][[\"timestamp\",\"station_id\",\"aqi\",\"z\"]].head()" },
    { type: "h2", text: "Census tract summaries" },
    { type: "code", lang: "python", code: "tracts[[\"population\",\"median_income\",\"diesel_pm\",\"tree_pct\"]].describe()" },
    { type: "code", lang: "python", code: "tracts.groupby(\"supervisor_district\")[\"diesel_pm\"].median()" },
    { type: "p", html: "When summarising tracts, decide whether each tract counts equally or you weight by population. Unweighted median tract income is not median income of residents." },
    { type: "h2", text: "Correlation" },
    { type: "p", html: "Pearson r from -1 to +1 measures linear co-movement. Positive: both rise together." },
    { type: "code", lang: "python", code: "tracts[\"tree_pct\"].corr(tracts[\"median_income\"])\ntracts.corr(numeric_only=True)" },
    { type: "code", lang: "r", code: "cor(tracts$tree_pct, tracts$median_income, use=\"complete.obs\")" },
    { type: "code", lang: "python", code: "import matplotlib.pyplot as plt\nplt.scatter(tracts[\"tree_pct\"], tracts[\"median_income\"], alpha=0.5)" },
    { type: "callout", html: "Correlation is not causation. r only captures linear relationships — always scatter-plot the pair.", variant: "warn", title: "Two caveats." },
    { type: "h2", text: "Missing data" },
    { type: "code", lang: "python", code: "print(aqi[\"aqi\"].isna().sum(), \"missing\")\nprint(aqi[\"aqi\"].count(), \"valid\")" },
    { type: "callout", html: "Every summary needs sample size: \"Median AQI was 52 (n = 18,400 hours)\".", variant: "tip", title: "Report n." },
    { type: "h2", text: "Comparing two groups" },
    { type: "code", lang: "python", code: "coastal = aqi[aqi[\"region\"]==\"coastal\"][\"aqi\"]\ninland = aqi[aqi[\"region\"]==\"inland\"][\"aqi\"]\nprint(\"coastal median:\", coastal.median(), \"inland median:\", inland.median())" },
    { type: "p", html: "A difference in medians is descriptive evidence. Formal significance tests come later — description comes first." },
    { type: "h2", text: "Writing up findings" },
    { type: "olist", items: ["State dataset, time range, and unit of observation.","Report centre, spread, and n; prefer median for skewed data.","Include one plot showing shape.","Mention outliers and whether they are kept.","Avoid causal language."] },
    { type: "callout", html: "Four datasets can share identical mean, std, and correlation yet look completely different. Numbers summarise; plots reveal.", variant: "note", title: "Anscombe's quartet." },
    { type: "exercise", html: "For hourly AQI with station and season: report mean, median, IQR; explain mean-median gap; plot histogram; compute 95th percentile; flag IQR outliers and inspect top 5. Is the distribution skewed? Which centre is typical?", title: "Profile LA air quality", hint: "describe() and quantile(); large mean-median gap signals right skew.", solution: { lang: "python", code: "s = aqi[\"aqi\"]\nprint(s.describe())\nq1,q3 = s.quantile([0.25,0.75]); iqr=q3-q1\ns.plot(kind=\"hist\", bins=40)\nout = aqi[(aqi[\"aqi\"]<q1-1.5*iqr)|(aqi[\"aqi\"]>q3+1.5*iqr)]\nprint(out.nlargest(5,\"aqi\")[[\"timestamp\",\"station_id\",\"aqi\"]])", note: "Report median as typical; discuss high outliers as episodic pollution." } },
    { type: "exercise", html: "Using diesel_pm and population: median and IQR of diesel_pm; population-weighted mean; median diesel_pm per supervisor_district; scatter diesel_pm vs median_income with correlation.", title: "Compare census tracts by burden", hint: "Weighted mean: sum(diesel_pm * population) / sum(population).", solution: { lang: "python", code: "d = tracts[\"diesel_pm\"]\nprint(\"median:\", d.median(), \"IQR:\", d.quantile(0.75)-d.quantile(0.25))\nwmean = (tracts[\"diesel_pm\"]*tracts[\"population\"]).sum()/tracts[\"population\"].sum()\nprint(tracts.groupby(\"supervisor_district\")[\"diesel_pm\"].median())\nprint(\"r:\", tracts[\"diesel_pm\"].corr(tracts[\"median_income\"]))", note: "Correlation does not imply income causes diesel exposure." } },
    { type: "exercise", html: "From daily tmax_c with month column: mean, median, std for summer and winter; density plot overlay; 99th percentile of summer daily maxima.", title: "Seasonal temperature characterisation", hint: "Filter by month; quantile(0.99) contextualises record heat.", solution: { lang: "r", code: "summer <- filter(temp, month %in% c(6,7,8))\nwinter <- filter(temp, month %in% c(12,1,2))\nsummary(summer$tmax_c)\nggplot(temp, aes(x=tmax_c, color=month %in% c(6,7,8))) + geom_density()\nquantile(summer$tmax_c, 0.99)", note: "Compare record daily max to P99 — a large gap means a true extreme." } },
    { type: "h2", text: "Recap" },
    { type: "list", items: ["Describe centre, spread, and shape before modelling.","Prefer median for skewed pollution and rainfall data.","Group summaries reveal geography and seasonality.","Investigate outliers — never silent-delete.","Correlation measures linear co-movement only; scatter-plot pairs."] },
  ]
};
