module.exports = {
  title: "Geospatial analysis",
  track: 'geo', tool: 'Both', level: 'advanced', time: "~6-8 hrs",
  lede: "Geospatial analysis treats location as data you can compute with. This comprehensive lesson covers CRS, spatial joins, buffers, and census-tract workflows in Python and R — turning \"which communities are within 1 km of a refinery?\" into reproducible code.",
  learn: [
    "Understand vector geometry: points, lines, polygons",
    "Work with coordinate reference systems and reprojection",
    "Load and plot spatial data with GeoPandas and sf",
    "Run spatial joins, buffers, and distance queries",
    "Aggregate by area and prepare choropleth data"
  ],
  prereqs: [{"id":"pandas","label":"pandas"},{"id":"maps","label":"Making maps"}],
  resources: [
    {
      "name": "GeoPandas user guide",
      "url": "https://geopandas.org/en/stable/docs/user_guide.html",
      "kind": "docs"
    },
    {
      "name": "Automating GIS Processes",
      "url": "https://autogis-site.readthedocs.io/",
      "kind": "course"
    },
    {
      "name": "epsg.io (find a CRS)",
      "url": "https://epsg.io/",
      "kind": "tool"
    }
  ],
  unlock: {"label":"Track California’s emitters","url":"projects.html","blurb":"Find which census tracts sit near major emitters using real spatial joins."},
  content: [
    { type: "p", html: "Geospatial analysis treats location as data you can compute with: distances, overlaps, containment, neighbourhoods. With GeoPandas (Python) and sf (R) you work in familiar tables plus a geometry column. This lesson covers census tracts, monitoring stations, and emitter facilities across LA and California." },
    { type: "callout", html: "This lesson focuses on vector data — points, lines, polygons. Gridded satellite rasters are covered in the gridded-remote-sensing lesson.", variant: "note", title: "Vector first." },
    { type: "h2", text: "Vector geometries" },
    { type: "table", head: ["Geometry","Represents","Environmental example"], rows: [["Point","Single location","AQI station, factory stack"],["LineString","Path","River, transmission line"],["Polygon","Area","Census tract, county, watershed"]] },
    { type: "code", lang: "python", code: "import geopandas as gpd\ntracts = gpd.read_file(\"la_tracts.geojson\")\nprint(tracts.crs)\ntracts.head()\ntracts.plot(edgecolor=\"gray\", facecolor=\"none\")" },
    { type: "h2", text: "GeoDataFrames" },
    { type: "p", html: "A <strong>GeoDataFrame</strong> is a pandas DataFrame with a special geometry column. Every spatial operation respects that column." },
    { type: "code", lang: "python", code: "type(tracts)          # GeoDataFrame\ntracts.geometry.type.value_counts()\ntracts[[\"geoid\", \"population\", \"geometry\"]].head()" },
    { type: "code", lang: "r", code: "library(sf)\ntracts <- st_read(\"la_tracts.geojson\")\nhead(tracts)" },
    { type: "h2", text: "Coordinate reference systems" },
    { type: "p", html: "A <strong>CRS</strong> defines what coordinates mean. EPSG:4326 (lat/lon degrees) is standard for storage and web maps. It is wrong for measuring distance — degrees are not constant length." },
    { type: "code", lang: "python", code: "print(tracts.crs)  # often EPSG:4326\ntracts_m = tracts.to_crs(epsg=3310)  # California Albers, metres\ntracts_m[\"area_km2\"] = tracts_m.area / 1e6" },
    { type: "callout", html: "Measuring in degrees gives nonsense. Two layers in different CRSs will not align. Confirm .crs on every layer; reproject to match; use metre CRS before distance or area.", variant: "warn", title: "The number one geospatial bug." },
    { type: "h2", text: "Reprojecting in R" },
    { type: "code", lang: "r", code: "tracts_m <- st_transform(tracts, 3310)\nst_area(tracts_m) / 1e6  # km2" },
    { type: "table", head: ["CRS","Units","Use for"], rows: [["EPSG:4326","Degrees","Storage, Folium, GeoJSON"],["EPSG:3310","Metres","California area and distance"],["EPSG:3857","Metres","Web tiles (approximate)"]] },
    { type: "h2", text: "Loading common formats" },
    { type: "list", items: ["<strong>GeoJSON:</strong> text-based, web-friendly — census tracts, city boundaries.","<strong>Shapefile:</strong> legacy standard — many government downloads.","<strong>GeoPackage:</strong> single-file replacement for shapefiles.","<strong>Parquet:</strong> fast columnar — increasingly common at scale."] },
    { type: "code", lang: "python", code: "stations = gpd.read_file(\"la_aqi_stations.geojson\")\nfacilities = gpd.read_file(\"ca_emitters.geojson\")" },
    { type: "h2", text: "Plotting maps" },
    { type: "code", lang: "python", code: "import matplotlib.pyplot as plt\nfig, ax = plt.subplots(figsize=(8, 8))\ntracts.plot(ax=ax, column=\"diesel_pm\", cmap=\"YlOrRd\", legend=True,\n            edgecolor=\"white\", linewidth=0.2)\nstations.plot(ax=ax, color=\"blue\", markersize=8)" },
    { type: "code", lang: "r", code: "library(ggplot2)\nggplot(tracts) +\n  geom_sf(aes(fill = diesel_pm), color = NA) +\n  scale_fill_viridis_c()" },
    { type: "h2", text: "Creating geometries from coordinates" },
    { type: "p", html: "Tables with lat/lon columns become point GeoDataFrames with GeoSeries or st_as_sf." },
    { type: "code", lang: "python", code: "from shapely.geometry import Point\ngdf = gpd.GeoDataFrame(\n    df,\n    geometry=[Point(lon, lat) for lon, lat in zip(df.lon, df.lat)],\n    crs=\"EPSG:4326\"\n)" },
    { type: "code", lang: "r", code: "pts <- st_as_sf(df, coords = c(\"lon\", \"lat\"), crs = 4326)" },
    { type: "h2", text: "Spatial joins" },
    { type: "p", html: "A <strong>spatial join</strong> attaches attributes by location — which tract contains each station? Which facilities fall in each county?" },
    { type: "code", lang: "python", code: "stations_m = stations.to_crs(tracts.crs)\ntagged = gpd.sjoin(stations_m, tracts, predicate=\"within\")\ntagged.groupby(\"geoid\")[\"station_id\"].count()" },
    { type: "code", lang: "r", code: "joined <- st_join(stations, tracts, join = st_within)" },
    { type: "callout", html: "within, contains, intersects, touches — choosing the right predicate is the heart of a spatial join. within requires the point inside the polygon; intersects is looser.", variant: "note", title: "Predicates matter." },
    { type: "h3", text: "Join types" },
    { type: "list", items: ["<strong>Point in polygon:</strong> tag stations with tract demographics.","<strong>Polygon overlap:</strong> which tracts touch a buffer zone?","<strong>Nearest:</strong> closest station to each tract centroid — use sjoin_nearest."] },
    { type: "code", lang: "python", code: "nearest = gpd.sjoin_nearest(tracts_m.set_geometry(tracts_m.centroid),\n                              stations_m, distance_col=\"dist_m\")" },
    { type: "h2", text: "Buffers and proximity" },
    { type: "p", html: "A <strong>buffer</strong> expands geometry by a distance. Buffer emitters by 1 km, then find intersecting tracts — who lives near major pollution sources?" },
    { type: "code", lang: "python", code: "fac_m = facilities.to_crs(epsg=3310)\nfac_m[\"buffer_1km\"] = fac_m.buffer(1000)\nfac_buf = fac_m.set_geometry(\"buffer_1km\")\nnear = gpd.sjoin(tracts_m, fac_buf, predicate=\"intersects\")" },
    { type: "callout", html: "buffer(1000) means 1000 metres only after reprojecting to a metre CRS. In EPSG:4326, 1000 means degrees — enormous.", variant: "warn", title: "Buffer in metres." },
    { type: "h2", text: "Distance calculations" },
    { type: "code", lang: "python", code: "from shapely.ops import nearest_points\np = stations_m.geometry.iloc[0]\ndistances = tracts_m.centroid.distance(p)\ndistances.min()  # metres in projected CRS" },
    { type: "code", lang: "r", code: "st_distance(stations[1,], tracts)" },
    { type: "h2", text: "Clipping to a region" },
    { type: "p", html: "Clip layers to LA County or a study bbox to speed plots and analysis." },
    { type: "code", lang: "python", code: "la_bbox = tracts.total_bounds  # minx, miny, maxx, maxy\nfac_la = gpd.clip(facilities.to_crs(tracts.crs), tracts)" },
    { type: "h2", text: "Dissolve and aggregate" },
    { type: "p", html: "Dissolve merges polygons by an ID — tract to district, parcel to zip — summing population or averaging burden scores." },
    { type: "code", lang: "python", code: "districts = tracts_m.dissolve(by=\"supervisor_district\", aggfunc={\"population\": \"sum\", \"diesel_pm\": \"mean\"})" },
    { type: "code", lang: "r", code: "districts <- tracts %>%\n  group_by(supervisor_district) %>%\n  summarise(pop = sum(population), diesel = mean(diesel_pm)) %>%\n  st_union()" },
    { type: "h2", text: "Choropleth preparation" },
    { type: "p", html: "Spatial join point counts to tract polygons, merge on geoid, plot — the analytical half of a choropleth map." },
    { type: "code", lang: "python", code: "counts = tagged.groupby(\"geoid\").size().rename(\"n_stations\")\nchoro = tracts.merge(counts, on=\"geoid\", how=\"left\").fillna(0)\nchoro.plot(column=\"n_stations\", cmap=\"Blues\", legend=True)" },
    { type: "callout", html: "geoid 6037000100 vs \"06037000100\" — strings and ints must match. Strip whitespace; zero-pad FIPS codes.", variant: "tip", title: "Join key hygiene." },
    { type: "h2", text: "Point maps vs choropleths" },
    { type: "list", items: ["<strong>Point map:</strong> exact locations — stations, facilities.","<strong>Choropleth:</strong> shaded areas — tract burden, county emissions.","<strong>Hexbin / kernel:</strong> dense points — alternative when choropleths mislead."] },
    { type: "p", html: "Choropleths on large tracts can hide hotspots. Pair with point layers when possible." },
    { type: "h2", text: "Interactive maps with Folium" },
    { type: "code", lang: "python", code: "import folium\nm = folium.Map(location=[34.05, -118.24], zoom_start=9)\nfolium.Choropleth(geo_data=choro.__geo_interface__,\n    data=choro, columns=[\"geoid\", \"diesel_pm\"], key_on=\"feature.properties.geoid\",\n    fill_color=\"YlOrRd\").add_to(m)" },
    { type: "h2", text: "sf in R: spatial verbs" },
    { type: "code", lang: "r", code: "library(dplyr)\nnear_tracts <- tracts %>%\n  mutate(cent = st_centroid(geometry)) %>%\n  st_join(facilities %>% st_buffer(dist = 1000), join = st_intersects)" },
    { type: "h2", text: "Census tract analysis workflow" },
    { type: "steps", items: ["Load tract polygons and confirm CRS.","Load facility or station points; reproject to match.","Spatial join or buffer + intersect.","Aggregate population or burden in affected tracts.","Map and report with units (people, tracts, km)."] },
    { type: "h2", text: "Population-weighted exposure" },
    { type: "p", html: "Counting tracts treats sparse desert equal to dense urban. Weight by population for people-near-source estimates." },
    { type: "code", lang: "python", code: "exposed_pop = near.groupby(\"geoid\")[\"population\"].first().sum()\ntotal_pop = tracts_m[\"population\"].sum()\nprint(\"fraction exposed:\", exposed_pop / total_pop)" },
    { type: "h2", text: "Topology and validity" },
    { type: "p", html: "Invalid polygons (self-intersections) break some operations. buffer(0) in shapely often repairs; st_make_valid in sf." },
    { type: "code", lang: "python", code: "tracts[\"geometry\"] = tracts.geometry.buffer(0)" },
    { type: "code", lang: "r", code: "tracts <- st_make_valid(tracts)" },
    { type: "h2", text: "Writing spatial outputs" },
    { type: "code", lang: "python", code: "choro.to_file(\"la_stations_per_tract.geojson\", driver=\"GeoJSON\")\nnear.to_parquet(\"tracts_near_emitters.parquet\")" },
    { type: "h2", text: "Common mistakes" },
    { type: "list", items: ["Plotting lon/lat without setting CRS.","Buffering in degrees.","Spatial join without matching CRS.","Mismatched join keys on choropleth.","Confusing centroid of tract with population centroid."] },
    { type: "exercise", html: "Load facility points and LA census tracts. Reproject to EPSG:3310, buffer facilities 1 km, find tracts intersecting buffers. How many tracts? What total population? Compare to county total.", title: "Who lives near emitters?", hint: "Order: match CRS, buffer(1000), sjoin intersects, sum population.", solution: { lang: "python", code: "tracts = gpd.read_file(\"la_tracts.geojson\")\nfac = gpd.read_file(\"ca_emitters.geojson\")\nt_m = tracts.to_crs(3310)\nf_m = fac.to_crs(3310)\nf_m[\"buf\"] = f_m.buffer(1000)\nbuf = f_m.set_geometry(\"buf\")\nnear = gpd.sjoin(t_m, buf, predicate=\"intersects\")\nprint(\"tracts:\", near[\"geoid\"].nunique())\nprint(\"population:\", near.drop_duplicates(\"geoid\")[\"population\"].sum())", note: "Deduplicate tracts before summing population — sjoin can duplicate rows per facility." } },
    { type: "exercise", html: "Spatial join AQI stations to tracts. Compute mean tract diesel_pm for stations in coastal vs inland regions (use a region column on tracts). Map stations coloured by tract median income.", title: "Tag stations with tract demographics", hint: "sjoin within; groupby region; merge attributes back to points for plotting.", solution: { lang: "python", code: "st = gpd.read_file(\"la_aqi_stations.geojson\").to_crs(tracts.crs)\ntagged = gpd.sjoin(st, tracts, predicate=\"within\")\nprint(tagged.groupby(\"coast_inland\")[\"diesel_pm\"].mean())\ntagged.plot(column=\"median_income\", cmap=\"viridis\", legend=True)", note: "Station inherits tract attributes via join — verify no stations fall outside all polygons (orphans)." } },
    { type: "exercise", html: "Using sf: dissolve tracts to supervisor districts, sum population, mean diesel burden, plot choropleth. Which district has highest mean diesel PM?", title: "District-level aggregation in R", hint: "group_by district + summarise + st_union or dissolve equivalent.", solution: { lang: "r", code: "library(sf)\nlibrary(dplyr)\ntracts <- st_read(\"la_tracts.geojson\") %>% st_transform(3310)\ndist <- tracts %>%\n  group_by(supervisor_district) %>%\n  summarise(pop = sum(population), diesel = mean(diesel_pm), .groups = \"drop\") %>%\n  st_union(by = supervisor_district)\nggplot(dist) + geom_sf(aes(fill = diesel)) + scale_fill_viridis_c()", note: "District means treat each tract equally unless you weight by population — state your choice." } },
    { type: "h2", text: "Recap" },
    { type: "list", items: ["Vector data = points, lines, polygons in a GeoDataFrame geometry column.","Know your CRS; reproject to metres before measuring.","Spatial joins attach data by location using predicates.","Buffers answer proximity questions; aggregate for choropleths.","Validate geometry, match join keys, weight by population when reporting exposure."] },
  ]
};
