module.exports = {
  title: "Git & GitHub basics",
  track: 'foundations', tool: 'Tool', level: 'beginner', time: "~4-5 hrs",
  lede: "Git tracks every change to your work so you can experiment freely and never lose anything; GitHub stores it online and makes it shareable. Both research and industry run on this workflow — and Terrain’s notebooks live on GitHub.",
  learn: [
    "Explain what version control solves for research and team projects",
    "Initialize a repository and make atomic commits",
    "Inspect history with log and diff",
    "Connect a local repo to GitHub and push/pull safely",
    "Use branches to try ideas without breaking main",
    "Write .gitignore to exclude data dumps and secrets",
    "Collaborate with pull requests and resolve simple conflicts",
    "Follow Terrain’s GitHub workflow for notebooks and projects"
  ],
  resources: [
    {
      "name": "GitHub Skills (interactive)",
      "url": "https://skills.github.com/",
      "kind": "course"
    },
    {
      "name": "Software Carpentry: Git",
      "url": "https://swcarpentry.github.io/git-novice/",
      "kind": "guide"
    },
    {
      "name": "GitHub Desktop (GUI)",
      "url": "https://desktop.github.com/",
      "kind": "tool"
    }
  ],
  unlock: {"label":"View a project notebook on GitHub","url":"projects.html","blurb":"Every project links to its notebook on GitHub — now the repo, commits and history will make sense."},
  content: [
    { type: "p", html: "Whether you are versioning a CalEnviroScreen analysis, a UCLA lab script, or a Terrain capstone notebook, Git is how you avoid <code>analysis_final_v3_REAL.ipynb</code> chaos. This lesson teaches the concepts and the command line; <a class=\"inline\" href=\"https://desktop.github.com/\" target=\"_blank\" rel=\"noopener\">GitHub Desktop</a> offers the same moves with buttons." },
    { type: "callout", html: "<strong>Git</strong> is the version-control program on your computer. <strong>GitHub</strong> is a website that hosts Git repositories online. You can use Git without GitHub, but Terrain shares projects via GitHub.", variant: "note", title: "Git vs. GitHub." },
    { type: "h2", text: "Why version control" },
    { type: "p", html: "Ever ended up with <code>analysis_final.py</code>, <code>analysis_final_v2.py</code>, <code>analysis_FINAL_actually.py</code>? Git replaces that mess with one folder and a complete, labelled history. You can see what changed, when, and why — and rewind to any point." },
    { type: "list", items: ["<strong>Git</strong> records snapshots of your project on your computer.","<strong>GitHub</strong> backs them up online and enables collaboration.","A project tracked by Git is a <strong>repository</strong> (repo).","Each saved snapshot is a <strong>commit</strong> with a message and author."] },
    { type: "p", html: "Environmental data work is iterative: new EPA release, corrected sensor, updated boundary file. Version control lets you branch to test a new cleaning rule, compare results, and merge only when satisfied." },
    { type: "h2", text: "Concepts in one picture" },
    { type: "table", head: ["Term","Meaning"], rows: [["<strong>Working directory</strong>","Files as you edit them right now"],["<strong>Staging area</strong>","Files marked to include in the next commit"],["<strong>Repository</strong>","The tracked history of commits"],["<strong>Remote</strong>","A copy on GitHub (or another server)"],["<strong>Branch</strong>","A parallel line of development"]] },
    { type: "callout", html: "<a class=\"inline\" href=\"https://desktop.github.com/\" target=\"_blank\" rel=\"noopener\">GitHub Desktop</a> does everything below with a friendly interface. Learn the concepts here; click the buttons there if you prefer.", variant: "tip", title: "Prefer buttons to commands?" },
    { type: "h2", text: "One-time setup" },
    { type: "p", html: "Install Git from <a class=\"inline\" href=\"https://git-scm.com/\" target=\"_blank\" rel=\"noopener\">git-scm.com</a>, then tell it who you are (this stamps your commits):" },
    { type: "code", lang: "bash", code: "git config --global user.name \"Your Name\"\ngit config --global user.email \"you@ucla.edu\"\n\ngit config --global init.defaultBranch main\ngit --version" },
    { type: "p", html: "Sign up for a free GitHub account at <a class=\"inline\" href=\"https://github.com/\" target=\"_blank\" rel=\"noopener\">github.com</a>. UCLA students can use GitHub Education perks for private repos and Codespaces." },
    { type: "h2", text: "Create a repository" },
    { type: "steps", items: [{"title":"Make a project folder","text":"<code>mkdir la-aqi-analysis && cd la-aqi-analysis</code>"},{"title":"Initialize Git","text":"<code>git init</code> creates a hidden <code>.git</code> directory that stores history."},{"title":"Add a README","text":"Describe the project: data source, goal, how to run the notebook."},{"title":"First commit","text":"Stage and commit — covered next."}] },
    { type: "code", lang: "bash", code: "mkdir la-aqi-analysis && cd la-aqi-analysis\ngit init\necho \"# LA AQI exploration\" > README.md" },
    { type: "h2", text: "The core loop: status, add, commit" },
    { type: "p", html: "Think of <code>git add</code> as putting items in a box, and <code>git commit</code> as sealing and labelling it. The <code>-m</code> message is that label." },
    { type: "code", lang: "bash", code: "git status          # what has changed?\ngit add README.md   # stage the file(s) you want to save\ngit commit -m \"Add README describing LA AQI project\"" },
    { type: "table", head: ["Command","What it does"], rows: [["<code>git status</code>","Shows changed, staged, and untracked files"],["<code>git add &lt;file&gt;</code>","Stages a file (<code>git add .</code> stages all changes)"],["<code>git commit -m \"...\"</code>","Saves a labelled snapshot"],["<code>git log --oneline</code>","Lists past commits, newest first"],["<code>git diff</code>","Shows unstaged edits line by line"]] },
    { type: "p", html: "Commit often with small, logical changes: \"Add data loading cell\", \"Fix CRS for California tracts\", \"Update chart labels\". Your future self reads the log like a lab notebook." },
    { type: "h3", text: "What not to commit" },
    { type: "list", items: ["API keys, passwords, <code>.env</code> files","Multi-gigabyte raw rasters or full CalEnviroScreen dumps (use releases or cloud storage)","Personal data subject to IRB restrictions","Generated outputs you can reproduce from code (optional — team preference)"] },
    { type: "h2", text: ".gitignore" },
    { type: "p", html: "A <code>.gitignore</code> file lists patterns Git should never track. Create one at the repo root:" },
    { type: "code", lang: "text", code: "# Secrets\n.env\n*.key\n\n# Data too large for GitHub\ndata/raw/*.csv\ndata/raw/*.tif\n\n# Python\n__pycache__/\n.ipynb_checkpoints/\n\n# macOS\n.DS_Store" },
    { type: "callout", html: "Once something is pushed to GitHub, assume it is public forever — even if you delete it later. Rotate any leaked API key immediately.", variant: "warn", title: "Don’t commit secrets or huge data." },
    { type: "h2", text: "Connecting to GitHub" },
    { type: "steps", items: [{"title":"Create a repo on GitHub","text":"On github.com click <strong>New</strong>, name it <code>la-aqi-analysis</code>, leave it empty (no README if you already have one locally)."},{"title":"Link your local folder","text":"Copy the HTTPS URL and add it as <code>origin</code>."},{"title":"Push","text":"Upload commits with <code>git push -u origin main</code>. Refresh GitHub — your files appear."}] },
    { type: "code", lang: "bash", code: "git remote add origin https://github.com/yourusername/la-aqi-analysis.git\ngit push -u origin main\n\n# later, after more commits:\ngit push                 # send new commits up\ngit pull                 # bring remote changes down" },
    { type: "callout", html: "<strong>Push</strong> sends your local commits to GitHub. <strong>Pull</strong> fetches and merges changes from GitHub. On a team, pull before you start working each day.", variant: "note", title: "Push vs. pull." },
    { type: "h2", text: "Clone an existing repo" },
    { type: "p", html: "To copy Terrain or a lab mate’s repo to your machine:" },
    { type: "code", lang: "bash", code: "git clone https://github.com/org/environmental-data-science.git\ncd environmental-data-science\nls notebooks/" },
    { type: "p", html: "<code>clone</code> downloads the full history. You can open notebooks locally in Jupyter or push copies to Colab." },
    { type: "h2", text: "Branches: experiment without fear" },
    { type: "p", html: "A <strong>branch</strong> is a parallel copy where you can try something risky — a new PM2.5 interpolation, a ggplot theme overhaul. If it works, merge it back; if not, delete the branch. <code>main</code> stays stable." },
    { type: "code", lang: "bash", code: "git switch -c explore-heat-map   # create and switch to new branch\n# ...edit notebook, git add, git commit...\ngit switch main                    # back to main line\ngit merge explore-heat-map         # fold in the work" },
    { type: "p", html: "List branches with <code>git branch</code>. Delete a merged branch with <code>git branch -d explore-heat-map</code>." },
    { type: "h2", text: "Pull requests on GitHub" },
    { type: "p", html: "For team projects, push a branch and open a <strong>Pull Request</strong> (PR) on GitHub. PRs show a diff, run checks, and invite review before merging to <code>main</code>. UCLA group projects and open-source Terrain contributions follow this flow." },
    { type: "olist", items: ["Push your feature branch: <code>git push -u origin explore-heat-map</code>","On GitHub, click <strong>Compare &amp; pull request</strong>","Describe what changed and link any issue","Reviewer comments; you push fixes to the same branch","Merge when approved"] },
    { type: "h2", text: "Merge conflicts (gentle introduction)" },
    { type: "p", html: "A conflict happens when two commits edit the same lines. Git marks the file:" },
    { type: "code", lang: "text", code: "<<<<<<< HEAD\nthreshold = 70\n=======\nthreshold = 100\n>>>>>>> explore-heat-map" },
    { type: "p", html: "Edit the file to keep the correct version (or combine), remove the markers, then <code>git add</code> and <code>git commit</code>. For notebooks, conflicts are painful — communicate who edits which sections, or use raw JSON merge tools sparingly. Clearing outputs reduces noise." },
    { type: "callout", html: "Running <code>git pull</code> before <code>git push</code> catches conflicts early on your machine instead of on GitHub.", variant: "tip", title: "Pull before you push." },
    { type: "h2", text: "Inspecting history" },
    { type: "code", lang: "bash", code: "git log --oneline --graph --all\ngit show HEAD              # patch for latest commit\ngit diff HEAD~1 HEAD -- README.md   # README change in last commit" },
    { type: "p", html: "Need an old version? <code>git checkout &lt;commit-hash&gt; -- path/to/file.ipynb</code> restores one file without rewinding the whole repo." },
    { type: "h2", text: "Undoing mistakes" },
    { type: "table", head: ["Situation","Command"], rows: [["Unstage a file","<code>git restore --staged file.py</code>"],["Discard unstaged edits","<code>git restore file.py</code>"],["Amend last commit message","<code>git commit --amend -m \"Better message\"</code>"],["Undo last commit, keep files","<code>git reset --soft HEAD~1</code>"]] },
    { type: "callout", html: "Do not <code>git push --force</code> to <code>main</code> on a shared repo unless your team explicitly agrees. It erases others’ work.", variant: "warn", title: "Never rewrite public history casually." },
    { type: "h2", text: "Writing good commit messages" },
    { type: "list", items: ["Present tense, imperative: \"Add AQI category function\", not \"added stuff\".","One logical change per commit — easier to review and revert.","Reference issues when relevant: \"Fix #12: handle NA in PM2.5 column\".","First line short; optional body explains why for bigger changes."] },
    { type: "p", html: "Good messages matter in environmental science where you must reproduce figures for a policy brief months later." },
    { type: "h2", text: "Terrain workflow" },
    { type: "p", html: "Terrain hosts curriculum and project notebooks on GitHub. Typical student flow:" },
    { type: "olist", items: ["Fork or clone the repo (or your fork)","Create a branch for your analysis","Open notebooks in Colab or locally; commit meaningful changes","Push and open a PR for feedback, or download .ipynb for submission"] },
    { type: "p", html: "Project pages link directly to the notebook source — now you know that \"View on GitHub\" is the canonical history of that analysis." },
    { type: "h2", text: "Authentication tips" },
    { type: "p", html: "GitHub no longer accepts account passwords for <code>git push</code>. Use a <strong>Personal Access Token</strong> (HTTPS) or SSH keys. GitHub Desktop handles this transparently; on the command line, follow GitHub’s \"Connecting to GitHub\" docs." },
    { type: "h2", text: "GitHub features worth knowing" },
    { type: "table", head: ["Feature","Use case"], rows: [["<strong>Issues</strong>","Track bugs and tasks (\"map legend wrong for LA county\")"],["<strong>Releases</strong>","Tag stable versions with zipped assets"],["<strong>Actions</strong>","Automated tests (CI) on each push"],["<strong>GitHub Pages</strong>","Host static sites (like Terrain skills pages)"]] },
    { type: "h2", text: "Collaboration norms" },
    { type: "list", items: ["Pull before starting work; push at logical stopping points.","Do not commit someone else’s huge data without asking.","Review PRs for reproducibility: can a teammate run the notebook cold?","Credit data sources (EPA, OEHHA, NASA) in README, not just in notebook prose."] },
    { type: "exercise", html: "Create a folder, <code>git init</code> it, add a <code>README.md</code> with one line about your project, and commit it. Add a second file <code>notes.txt</code>, commit again, and run <code>git log --oneline</code> to see your history.", title: "Make your first three commits", hint: "The loop is always: edit → <code>git add</code> → <code>git commit -m \"...\"</code>.", solution: { lang: "bash", code: "mkdir terrain-practice && cd terrain-practice\ngit init\necho \"# LA air quality practice repo\" > README.md\ngit add README.md\ngit commit -m \"Add README\"\n\necho \"Data: South Coast AQMD daily AQI\" > notes.txt\ngit add notes.txt\ngit commit -m \"Add data source notes\"\n\ngit log --oneline" } },
    { type: "exercise", html: "In your practice repo, create <code>.gitignore</code> that ignores <code>.env</code>, <code>*.csv</code> in a <code>data/raw/</code> folder, and <code>.ipynb_checkpoints/</code>. Run <code>git status</code> to confirm a dummy <code>data/raw/sample.csv</code> is untracked.", title: "Write a .gitignore for a data project", hint: "Patterns are one per line. Use <code>data/raw/*.csv</code>.", solution: { lang: "text", code: ".env\ndata/raw/*.csv\n.ipynb_checkpoints/\n.DS_Store" } },
    { type: "exercise", html: "Create branch <code>add-threshold</code>, add a line to <code>notes.txt</code> with an AQI threshold value, commit, switch back to <code>main</code>, and merge. Verify with <code>git log --oneline --graph</code>.", title: "Branch and merge", hint: "<code>git switch -c add-threshold</code>, edit, commit, <code>git switch main</code>, <code>git merge add-threshold</code>.", solution: { lang: "bash", code: "git switch -c add-threshold\necho \"Alert threshold: AQI 100\" >> notes.txt\ngit add notes.txt\ngit commit -m \"Document AQI alert threshold\"\ngit switch main\ngit merge add-threshold\ngit log --oneline --graph" } },
    { type: "h2", text: "Recap" },
    { type: "list", items: ["Git records labelled <strong>commits</strong>; GitHub hosts and shares them.","Loop: <code>git status</code> → <code>git add</code> → <code>git commit</code> → <code>git push</code>.","Use <code>.gitignore</code> for secrets and large raw environmental datasets.","<strong>Branches</strong> and <strong>pull requests</strong> enable safe collaboration.","Terrain project notebooks on GitHub are the source of truth — clone, branch, and contribute.","Next: open any <a class=\"inline\" href=\"projects.html\">Terrain project</a> on GitHub and read its commit history with fresh eyes."] },
  ]
};
