module.exports = {
  title: "Notebooks & Google Colab",
  track: 'foundations', tool: 'Tool', level: 'beginner', time: "~2-3 hrs",
  lede: "A notebook lets you run code in small chunks, see results instantly, and mix in notes and charts. Google Colab gives you one free in the browser with nothing to install — and every Terrain Python project opens directly in it.",
  learn: [
    "Understand cells and how a notebook runs",
    "Open and run a notebook in Google Colab",
    "Mix code, output and Markdown notes effectively",
    "Use keyboard shortcuts and runtime controls",
    "Install packages and load environmental datasets",
    "Avoid the classic out-of-order execution trap",
    "Save your work to Drive, download .ipynb, or push to GitHub"
  ],
  video: {
    label: "Watch walkthrough",
    url: "https://drive.google.com/file/d/1QoQ5489piIQTTe_u59eXbb0vjXiz_xtd/view",
    note: "Intro to Google Colab with a Terrain mentor (opens in Google Drive)."
  },
  resources: [
    {
      "name": "Terrain walkthrough: Intro to Google Colab",
      "url": "https://drive.google.com/file/d/1QoQ5489piIQTTe_u59eXbb0vjXiz_xtd/view",
      "kind": "video"
    },
    {
      "name": "Welcome to Colab",
      "url": "https://colab.research.google.com/",
      "kind": "guide"
    },
    {
      "name": "Jupyter documentation",
      "url": "https://docs.jupyter.org/en/latest/",
      "kind": "docs"
    }
  ],
  unlock: {"label":"Browse starter projects","url":"projects.html","blurb":"Every Python project has an \"Open in Colab\" button — now you know exactly what to do with it."},
  content: [
    { type: "p", html: "If you completed <a class=\"inline\" href=\"lesson.html?id=python-fundamentals\">Python fundamentals</a> in Colab, you already have the core skill: run a cell, see output. This lesson goes deeper on how notebooks work, how to stay organised on real Terrain projects (LA air quality, California emitters, heat waves), and how to avoid the mistakes that make notebooks feel \"haunted\"." },
    { type: "callout", html: "Exploratory work is messy. You load a CSV, plot a map, notice a bad sensor, filter, replot. Notebooks let you interleave code, charts, and notes so your future self (and collaborators) can follow the story.", variant: "note", title: "Why notebooks for environmental data?" },
    { type: "h2", text: "What a notebook is" },
    { type: "p", html: "A notebook is a document made of <strong>cells</strong>. A <em>code cell</em> holds a few lines of Python (or R); run it and the output appears right below. A <em>text (Markdown) cell</em> holds formatted notes. Because you run small pieces at a time and see results immediately, notebooks are ideal for exploring data." },
    { type: "list", items: ["<strong>Interactive:</strong> change one filter, rerun one cell, see the chart update.","<strong>Visual:</strong> tables and plots render inline — no switching windows.","<strong>Documented:</strong> Markdown cells explain <em>why</em>, not just <em>what</em>.","<strong>Shareable:</strong> one <code>.ipynb</code> file holds code, output, and narrative."] },
    { type: "callout", html: "\"Jupyter\" is the underlying notebook technology; \"Colab\" is Google’s free hosted version that runs in your browser on Google’s computers. Same <code>.ipynb</code> files, zero setup.", variant: "note", title: "Jupyter vs. Colab." },
    { type: "h2", text: "The notebook file: .ipynb" },
    { type: "p", html: "Under the hood, a notebook is JSON: an ordered list of cells, each with source code or Markdown and optional output. You rarely edit the JSON by hand — Colab and Jupyter provide the UI. Terrain stores project notebooks on GitHub; clicking <strong>Open in Colab</strong> loads that file into a fresh runtime." },
    { type: "table", head: ["Piece","What it stores"], rows: [["<code>cells</code>","Ordered list of code or Markdown blocks"],["<code>metadata</code>","Kernel type (Python version), Colab-specific settings"],["<code>outputs</code>","Printed text, tables, images from executed code"]] },
    { type: "h2", text: "Open and run your first notebook" },
    { type: "steps", items: [{"title":"Go to Colab","text":"Visit <a class=\"inline\" href=\"https://colab.research.google.com/\" target=\"_blank\" rel=\"noopener\">colab.research.google.com</a> and sign in with a Google account."},{"title":"New notebook","text":"Click <strong>New notebook</strong>. You get one empty code cell."},{"title":"Type some code","text":"Click the cell and enter <code>print(\"hello, Terrain\")</code>."},{"title":"Run it","text":"Press <strong>Shift + Enter</strong> (or the play button). The output appears below and a new cell opens."}] },
    { type: "code", lang: "python", code: "print(\"hello, Terrain\")\n2 + 2\n# hello, Terrain\n# 4" },
    { type: "p", html: "Notice the last line’s value (<code>4</code>) shows even without <code>print()</code> — a notebook displays the result of the final expression in a cell." },
    { type: "h2", text: "Cell types and the toolbar" },
    { type: "p", html: "Use the toolbar or shortcuts to add cells. The cell type dropdown switches between <strong>Code</strong> and <strong>Text</strong> (Markdown):" },
    { type: "table", head: ["Action","Shortcut / control"], rows: [["Run cell","<strong>Shift + Enter</strong>"],["Run cell, stay in place","<strong>Ctrl/Cmd + Enter</strong>"],["Add code cell below","<strong>Code</strong> button or <strong>B</strong> in command mode"],["Add text cell","<strong>+ Text</strong>"],["Delete cell","Click cell, press <strong>D D</strong> (command mode)"]] },
    { type: "callout", html: "A blue bar on the left means <em>command mode</em> (cell selected, keyboard shortcuts work). A green border means <em>edit mode</em> (you are typing inside the cell). Press <strong>Esc</strong> to leave edit mode.", variant: "tip", title: "Command mode vs. edit mode." },
    { type: "h2", text: "Cells run in the order you run them" },
    { type: "p", html: "This is the one thing that trips everyone up. A notebook remembers variables across cells, but only in the order you actually <em>execute</em> them — not top-to-bottom on the page. The little number <code>[1]</code>, <code>[2]</code> next to each cell shows the run order." },
    { type: "code", lang: "python", code: "# Cell 1 — run first\nx = 5\n\n# Cell 2 — run second\nprint(x * 2)   # 10\n\n# Now edit Cell 1 to x = 9 but forget to re-run.\n# Cell 2 still prints 10 until you run Cell 1 again." },
    { type: "callout", html: "If you define <code>x = 5</code>, run it, then edit it to <code>x = 9</code> but forget to re-run, later cells still see <code>5</code>. When results look wrong, use <strong>Runtime → Restart and run all</strong> to execute cleanly from the top.", variant: "warn", title: "The out-of-order trap." },
    { type: "h3", text: "Restarting the runtime" },
    { type: "p", html: "Colab gives you a fresh Python process on Google’s server. <strong>Runtime → Restart runtime</strong> wipes all variables. Use it when:" },
    { type: "list", items: ["Outputs disagree with the code on screen","You installed a package and need a clean import","You ran cells in a confusing order and want a reset"] },
    { type: "p", html: "<strong>Restart and run all</strong> is the gold standard before sharing or submitting a notebook — it proves the notebook works top to bottom." },
    { type: "h2", text: "Add notes with Markdown" },
    { type: "p", html: "Click <strong>+ Text</strong> to add a Markdown cell for headings and explanations. A little formatting goes a long way toward a notebook others (and future-you) can follow." },
    { type: "code", lang: "text", code: "# LA Air Quality — Week 1 exploration\n## Data source\n\nReadings from South Coast AQMD monitoring stations.\n\n- **AQI**: Air Quality Index\n- **PM2.5**: fine particulate matter\n\n[CalEnviroScreen documentation](https://oehha.ca.gov/calenviroscreen)" },
    { type: "p", html: "Use headings to mirror your analysis sections: Load → Clean → Explore → Model → Export. Terrain project notebooks follow this pattern." },
    { type: "h2", text: "Running Terrain projects in Colab" },
    { type: "steps", items: [{"title":"Open projects.html","text":"Browse the Terrain project library."},{"title":"Click Open in Colab","text":"Colab opens a copy linked to the GitHub notebook."},{"title":"Runtime → Run all","text":"Execute every cell in order. First run may take a minute while packages load."},{"title":"Save a copy","text":"File → Save a copy in Drive so your changes do not overwrite the original link."}] },
    { type: "callout", html: "Terrain notebooks usually explain the dataset (e.g. LA AQI stations, Climate TRACE emitters) in the first few text cells. Read them before changing code.", variant: "tip", title: "Read the top Markdown cells." },
    { type: "h2", text: "Installing packages" },
    { type: "p", html: "Most data libraries (pandas, matplotlib, geopandas on many runtimes) are pre-installed in Colab. If one is missing, install it in a cell with <code>!pip</code> — the <code>!</code> runs a shell command:" },
    { type: "code", lang: "bash", code: "!pip install geopandas" },
    { type: "p", html: "Pin versions for reproducibility when a project requires it:" },
    { type: "code", lang: "bash", code: "!pip install \"pandas>=2.0\"" },
    { type: "callout", html: "After installing, you may need <strong>Runtime → Restart runtime</strong> before <code>import</code> works. Colab will remind you.", variant: "note" },
    { type: "h2", text: "Loading data in Colab" },
    { type: "h3", text: "From a URL (most Terrain projects)" },
    { type: "p", html: "Reproducible notebooks read CSV or GeoJSON straight from the web — no manual upload:" },
    { type: "code", lang: "python", code: "import pandas as pd\n\nurl = \"https://raw.githubusercontent.com/example/la_aqi.csv\"\ndf = pd.read_csv(url)\ndf.head()" },
    { type: "h3", text: "Upload from your computer" },
    { type: "p", html: "Click the folder icon in the left sidebar, then the upload button. Files land in <code>/content/</code> and disappear when the runtime ends unless you copy them to Drive." },
    { type: "code", lang: "python", code: "from google.colab import files\nuploaded = files.upload()   # pick a local CSV\n# then read with pandas" },
    { type: "h3", text: "Mount Google Drive" },
    { type: "p", html: "For persistent files, mount your Drive:" },
    { type: "code", lang: "python", code: "from google.colab import drive\ndrive.mount(\"/content/drive\")\n# read: pd.read_csv(\"/content/drive/MyDrive/data/ces.csv\")" },
    { type: "h2", text: "Charts and maps inline" },
    { type: "p", html: "Matplotlib figures appear automatically below the cell that creates them:" },
    { type: "code", lang: "python", code: "import matplotlib.pyplot as plt\n\nstations = [\"Downtown LA\", \"Pasadena\", \"Long Beach\"]\naqi = [72, 65, 80]\n\nplt.bar(stations, aqi, color=\"steelblue\")\nplt.axhline(100, color=\"red\", linestyle=\"--\", label=\"Unhealthy\")\nplt.ylabel(\"AQI\")\nplt.title(\"Sample LA stations\")\nplt.legend()\nplt.show()" },
    { type: "p", html: "Interactive maps (folium, leafmap) render HTML in the output area — ideal for exploring CalEnviroScreen tracts or emitter locations." },
    { type: "h2", text: "Secrets and API keys" },
    { type: "p", html: "Some climate and air-quality APIs need a key. Never paste keys into a notebook you will push to GitHub. Colab offers a <strong>Secrets</strong> panel (key icon) to store them safely:" },
    { type: "olist", items: ["Open Secrets, add a name (e.g. <code>EPA_API_KEY</code>) and value","In code: <code>from google.colab import userdata; key = userdata.get(\"EPA_API_KEY\")</code>","Keep notebooks public-safe — keys stay in your Colab account"] },
    { type: "callout", html: "If you download a notebook that once contained a key, scrub it before sharing. See the <a class=\"inline\" href=\"lesson.html?id=git-github\">Git &amp; GitHub lesson</a> on <code>.gitignore</code>.", variant: "warn", title: "Do not commit keys." },
    { type: "h2", text: "Saving your work" },
    { type: "list", items: ["<strong>File → Save a copy in Drive</strong> keeps it in your Google Drive (most common).","<strong>File → Download → .ipynb</strong> saves a local copy you can share or commit to GitHub.","Colab autosaves to Drive as you work, but get in the habit of saving deliberately before closing the tab."] },
    { type: "p", html: "Downloaded notebooks may include large embedded outputs (big maps). Use <strong>Edit → Clear all outputs</strong> before committing to git to keep repos small." },
    { type: "h2", text: "Hardware accelerator (optional)" },
    { type: "p", html: "<strong>Runtime → Change runtime type</strong> lets you request a GPU. Most Terrain introductory projects use pandas and matplotlib on CPU — you do not need a GPU until deep-learning or heavy raster work." },
    { type: "h2", text: "Collaboration and commenting" },
    { type: "p", html: "Share a Drive-saved notebook like any Google Doc: simultaneous editors, comment threads on cells, and version history. For coursework at UCLA, instructors often ask for a Drive link with comment access." },
    { type: "h2", text: "Notebook hygiene checklist" },
    { type: "olist", items: ["Restart and run all before submitting","Markdown explains each major step","No absolute paths that only work on your laptop","No API keys in the file","Outputs cleared if the file is huge"] },
    { type: "h2", text: "When not to use a notebook" },
    { type: "p", html: "Notebooks excel at exploration. For production pipelines (nightly ETL, deployed APIs), plain <code>.py</code> scripts are easier to test and schedule. Many researchers prototype in Colab, then refactor stable code into modules." },
    { type: "exercise", html: "Create a new Colab notebook with: (1) a Markdown title cell for \"LA AQI snapshot\", (2) a code cell that defines a list of three station names and AQI values, (3) a code cell that prints the average AQI, (4) run all cells in order and confirm the execution numbers are sequential.", title: "Build a mini analysis notebook", hint: "Use <code>sum(aqi)/len(aqi)</code> or <code>statistics.mean</code>. Check <code>[1]</code>, <code>[2]</code>, <code>[3]</code> on each cell.", solution: { lang: "python", code: "# Markdown cell: # LA AQI snapshot\n\nstations = [\"Downtown LA\", \"Pasadena\", \"Long Beach\"]\naqi = [72, 65, 80]\n\navg = sum(aqi) / len(aqi)\nprint(f\"Average AQI: {avg:.1f}\")\n# Average AQI: 72.3" } },
    { type: "exercise", html: "In Colab, create two cells: Cell A sets <code>threshold = 70</code>, Cell B prints <code>aqi > threshold</code> for <code>aqi = 80</code>. Run B before A and observe the error. Then run A then B. Edit A to <code>threshold = 100</code>, run only B without re-running A — notice the stale result. Fix with Restart and run all.", title: "Fix an out-of-order bug", hint: "The execution order numbers tell the story. Restart runtime clears stale state.", solution: { lang: "python", code: "# Cell A\nthreshold = 70\n\n# Cell B\naqi = 80\nprint(aqi > threshold)   # True when threshold is 70\n\n# After changing A to threshold = 100, must re-run A\n# or use Runtime -> Restart and run all" } },
    { type: "exercise", html: "In a new code cell, use pandas to read the classic Iris CSV from a public URL, show <code>head()</code> and <code>shape</code>. Practice the pattern Terrain uses for environmental CSVs.", title: "Load a CSV from a URL", hint: "<code>import pandas as pd</code> then <code>pd.read_csv(url)</code>.", solution: { lang: "python", code: "import pandas as pd\n\nurl = \"https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv\"\ndf = pd.read_csv(url)\nprint(df.head())\nprint(df.shape)\n# (150, 5)" } },
    { type: "h2", text: "Recap" },
    { type: "list", items: ["Notebooks mix <strong>code cells</strong> and <strong>Markdown cells</strong> in one <code>.ipynb</code> file.","Run with <strong>Shift + Enter</strong>; execution order matters more than page order.","<strong>Restart and run all</strong> is your sanity check before sharing.","Terrain projects open directly in Colab — save a copy to Drive before editing.","Load data from URLs when possible; use Secrets for API keys, never hard-code them.","Ready for <a class=\"inline\" href=\"projects.html\">starter projects</a> or deeper <a class=\"inline\" href=\"lesson.html?id=pandas\">pandas</a> work."] },
    { type: "callout", html: "That is genuinely all you need to start. Head to the <a class=\"inline\" href=\"projects.html\">projects library</a>, click <strong>Open in Colab</strong> on any Python project, and run the cells top to bottom.", variant: "tip", title: "You’re ready." },
  ]
};
