module.exports = {
  title: "Regression & relationships",
  track: 'stats', tool: 'Both', level: 'intermediate', time: "~5-6 hrs",
  lede: "Regression is the workhorse of quantitative environmental analysis: model how AQI depends on weather, how emissions scale with capacity, and how predictors combine. This comprehensive lesson builds intuition, diagnostics, and interpretation in Python and R.",
  learn: [
    "Fit and read a simple linear regression",
    "Interpret slope, intercept, confidence intervals, and R-squared",
    "Extend to multiple predictors and categorical variables",
    "Diagnose models with residual plots",
    "Use transforms, interactions, and know what regression cannot claim"
  ],
  prereqs: [{"id":"descriptive-stats","label":"Descriptive statistics"}],
  resources: [
    {
      "name": "StatQuest: linear regression",
      "url": "https://www.youtube.com/watch?v=nk2CQITm_eo",
      "kind": "video"
    },
    {
      "name": "Introduction to Statistical Learning",
      "url": "https://www.statlearning.com/",
      "kind": "book"
    },
    {
      "name": "statsmodels OLS guide",
      "url": "https://www.statsmodels.org/stable/regression.html",
      "kind": "docs"
    }
  ],
  unlock: {"label":"Track California’s emitters","url":"projects.html","blurb":"Model what predicts a facility’s emissions and quantify the relationships."},
  content: [
    { type: "p", html: "Regression models how one variable depends on others. In environmental work you might ask: does daily temperature predict AQI? Do wind speed and season explain pollution after accounting for temperature? This lesson builds intuition first, then fits models in Python and R with air-quality and emissions examples." },
    { type: "callout", html: "Always scatter your outcome against each predictor. A straight line only makes sense if the cloud looks roughly linear. Curves, thresholds, and clusters need different tools.", variant: "note", title: "Plot before you model." },
    { type: "h2", text: "The idea: a line through the cloud" },
    { type: "p", html: "Simple linear regression fits the best straight line through scatter points: <strong>y = intercept + slope * x</strong>. \"Best\" means minimising the sum of squared vertical distances (ordinary least squares, OLS)." },
    { type: "code", lang: "python", code: "import matplotlib.pyplot as plt\nplt.scatter(aq[\"temp_c\"], aq[\"aqi\"], alpha=0.4)\nplt.xlabel(\"Temperature (C)\"); plt.ylabel(\"AQI\")" },
    { type: "list", items: ["<strong>Outcome (y):</strong> what you are trying to explain — AQI, emissions, stream flow.","<strong>Predictor (x):</strong> what you think helps explain y — temperature, wind, land cover.","<strong>Residual:</strong> actual minus predicted — what the model misses."] },
    { type: "h2", text: "Loading and preparing data" },
    { type: "p", html: "Merge daily AQI with weather on date. Drop rows with missing values before fitting — OLS ignores NaN but your n should be explicit." },
    { type: "code", lang: "python", code: "import pandas as pd\naq = pd.read_csv(\"la_daily_aqi_weather.csv\", parse_dates=[\"date\"])\naq = aq.dropna(subset=[\"aqi\", \"temp_c\", \"wind_ms\"])\nprint(len(aq), \"complete days\")" },
    { type: "code", lang: "r", code: "library(readr)\naq <- read_csv(\"la_daily_aqi_weather.csv\") %>%\n  filter(!is.na(aqi), !is.na(temp_c), !is.na(wind_ms))" },
    { type: "h2", text: "Fitting simple linear regression" },
    { type: "h3", text: "Python with statsmodels" },
    { type: "p", html: "statsmodels formula API reads like the question. It returns a full statistical summary." },
    { type: "code", lang: "python", code: "import statsmodels.formula.api as smf\nmodel = smf.ols(\"aqi ~ temp_c\", data=aq).fit()\nprint(model.summary())" },
    { type: "h3", text: "R with lm()" },
    { type: "code", lang: "r", code: "model <- lm(aqi ~ temp_c, data = aq)\nsummary(model)" },
    { type: "h2", text: "Reading the output" },
    { type: "table", head: ["Quantity","What it tells you"], rows: [["<strong>Slope</strong>","Predicted change in y per one-unit increase in x"],["<strong>Intercept</strong>","Predicted y when x = 0 (often not meaningful alone)"],["<strong>p-value</strong>","Evidence the slope is not just noise (small = stronger)"],["<strong>R-squared</strong>","Fraction of variance in y explained (0 to 1)"],["<strong>Std err / CI</strong>","Uncertainty around the slope estimate"]] },
    { type: "p", html: "Example: \"Each +1 degree C is associated with +2.8 AQI points (p &lt; 0.001), and temperature explains 38% of daily AQI variation (R2 = 0.38).\" Use <em>associated with</em>, not <em>causes</em>." },
    { type: "callout", html: "High R2 does not mean the model is correct. Low R2 can still describe a real effect — environmental relationships are noisy. Do not chase R2 at the expense of sense.", variant: "warn", title: "R-squared is not everything." },
    { type: "h2", text: "Interpreting slope in context" },
    { type: "p", html: "Slope units matter. A slope of 2.8 on AQI per degree C is modest day-to-day but large over a 10-degree heat wave. Translate coefficients into scenarios your audience understands." },
    { type: "code", lang: "python", code: "slope = model.params[\"temp_c\"]\nprint(\"At +5C:\", slope * 5, \"AQI points\")\nprint(\"At +10C:\", slope * 10, \"AQI points\")" },
    { type: "callout", html: "Intercept is predicted AQI at 0C — outside your data range and not meaningful. Focus on slope and confidence interval.", variant: "note", title: "Intercept traps." },
    { type: "h2", text: "Confidence intervals" },
    { type: "p", html: "A 95% confidence interval for the slope is the range of values consistent with the data. If it excludes zero, evidence for an association is stronger." },
    { type: "code", lang: "python", code: "ci = model.conf_int().loc[\"temp_c\"]\nprint(\"95% CI:\", ci[0], \"to\", ci[1])" },
    { type: "code", lang: "r", code: "confint(model, \"temp_c\", level = 0.95)" },
    { type: "h2", text: "Multiple regression" },
    { type: "p", html: "Add predictors with +. Each slope is the effect of that variable <em>holding others constant</em> — separating tangled influences like temperature and wind." },
    { type: "code", lang: "python", code: "model2 = smf.ols(\"aqi ~ temp_c + wind_ms + C(season)\", data=aq).fit()\nprint(model2.summary())" },
    { type: "code", lang: "r", code: "model2 <- lm(aqi ~ temp_c + wind_ms + season, data = aq)\nsummary(model2)" },
    { type: "callout", html: "Wrap categories in C(...) in Python. R treats factors automatically. Coefficients compare each level to a baseline season.", variant: "note", title: "Categorical predictors." },
    { type: "h3", text: "When slopes change" },
    { type: "p", html: "Adding a correlated predictor can shrink another slope — the new variable explains part of the original effect (confounding). Temperature and season overlap; adding season may reduce the temperature coefficient." },
    { type: "list", items: ["<strong>Confounding:</strong> a third variable drives both x and y.","<strong>Mediation:</strong> x affects a middle variable that affects y.","<strong>Collinearity:</strong> predictors are nearly redundant — unstable coefficients."] },
    { type: "h2", text: "Standardised coefficients" },
    { type: "p", html: "Compare predictors on different scales by standardising (z-scoring) first. A larger absolute standardised coefficient suggests a stronger linear association in standard-deviation units." },
    { type: "code", lang: "python", code: "aq_std = aq.copy()\nfor col in [\"aqi\", \"temp_c\", \"wind_ms\"]:\n    aq_std[col] = (aq[col] - aq[col].mean()) / aq[col].std()\nm_std = smf.ols(\"aqi ~ temp_c + wind_ms\", data=aq_std).fit()\nprint(m_std.params)" },
    { type: "h2", text: "Model assumptions" },
    { type: "p", html: "OLS assumes linearity, independent errors, constant variance, and normally distributed residuals (for inference). Check with plots, not trust alone." },
    { type: "steps", items: ["Scatter y vs each x — linear pattern?","Plot residuals vs fitted values — random cloud, no curve?","Plot residuals vs each predictor — no funnel shape?","Check influential points — does one day swing the line?"] },
    { type: "h2", text: "Residual diagnostics" },
    { type: "code", lang: "python", code: "import matplotlib.pyplot as plt\nfig, axes = plt.subplots(1, 2, figsize=(10, 4))\naxes[0].scatter(model.fittedvalues, model.resid, alpha=0.4)\naxes[0].axhline(0, color=\"red\")\naxes[0].set_xlabel(\"Fitted\"); axes[0].set_ylabel(\"Residual\")\naxes[1].scatter(aq[\"temp_c\"], model.resid, alpha=0.4)\naxes[1].axhline(0, color=\"red\")\nplt.tight_layout()" },
    { type: "list", items: ["<strong>Linearity:</strong> residuals vs fitted should show no curve.","<strong>Homoscedasticity:</strong> spread should not fan out with fitted values.","<strong>Independence:</strong> time series violate this — see the time-series lesson.","<strong>Outliers:</strong> large residuals warrant investigation."] },
    { type: "callout", html: "Daily AQI rows are not independent — yesterday affects today. Regression p-values may be over-confident. For time-stamped data, consider time-series methods or clustered errors.", variant: "warn", title: "Independence and time." },
    { type: "h2", text: "Influential points" },
    { type: "p", html: "One wildfire day can lever the whole line. Compare coefficients with and without high-leverage points." },
    { type: "code", lang: "python", code: "aq_no_fire = aq[aq[\"aqi\"] < 200]\nm_clean = smf.ols(\"aqi ~ temp_c\", data=aq_no_fire).fit()\nprint(\"full slope:\", model.params[\"temp_c\"])\nprint(\"no extreme slope:\", m_clean.params[\"temp_c\"])" },
    { type: "h2", text: "Polynomial and log transforms" },
    { type: "h3", text: "Curved relationships" },
    { type: "p", html: "If the scatter curves, add polynomial terms: temp_c + I(temp_c**2) in Python, or poly(temp_c, 2) in R." },
    { type: "code", lang: "python", code: "model_poly = smf.ols(\"aqi ~ temp_c + I(temp_c**2)\", data=aq).fit()\nprint(model_poly.rsquared)" },
    { type: "h3", text: "Log transforms for skew" },
    { type: "p", html: "Right-skewed outcomes (emissions, concentration) often model better on log scale. Interpret slope as approximate percent change." },
    { type: "code", lang: "python", code: "import numpy as np\naq[\"log_emit\"] = np.log1p(aq[\"co2_tons\"])\nsmf.ols(\"log_emit ~ capacity_mw\", data=facilities).fit().summary()" },
    { type: "h2", text: "Interactions" },
    { type: "p", html: "An interaction lets the slope of one predictor depend on another — e.g. temperature effect on AQI might be stronger in summer." },
    { type: "code", lang: "python", code: "smf.ols(\"aqi ~ temp_c * C(season)\", data=aq).fit().summary()" },
    { type: "callout", html: "With temp_c * season, each season gets its own temperature slope relative to the baseline. Plot separate lines by season to verify.", variant: "note", title: "Interaction interpretation." },
    { type: "h2", text: "Categorical outcomes? Use logistic regression" },
    { type: "p", html: "Binary outcomes — exceedance of AQI 100 yes/no — need logistic regression, not OLS. This lesson focuses on numeric outcomes; the idea of coefficients and p-values carries over." },
    { type: "code", lang: "python", code: "import statsmodels.api as sm\naq[\"bad_day\"] = (aq[\"aqi\"] >= 100).astype(int)\nlogit = sm.Logit(aq[\"bad_day\"], sm.add_constant(aq[[\"temp_c\", \"wind_ms\"]])).fit()\nprint(logit.summary())" },
    { type: "h2", text: "Prediction" },
    { type: "p", html: "Use predict() on new rows with the same columns the model was trained on." },
    { type: "code", lang: "python", code: "new = pd.DataFrame({\"temp_c\": [32, 38], \"wind_ms\": [2, 1], \"season\": [\"summer\", \"summer\"]})\nmodel2.predict(new)" },
    { type: "callout", html: "A model fit on 10-35C says little about 50C. Predicting outside the data range is guesswork. Check new data falls within training ranges.", variant: "warn", title: "Do not extrapolate." },
    { type: "h2", text: "Emissions example: facility data" },
    { type: "p", html: "California emitter inventories pair facility capacity with annual CO2. Multiple regression can ask whether capacity predicts emissions after controlling for sector." },
    { type: "code", lang: "python", code: "fac = pd.read_csv(\"ca_emitters.csv\")\nm_fac = smf.ols(\"co2_tons ~ capacity_mw + C(sector)\", data=fac).fit()\nprint(m_fac.params.head())" },
    { type: "p", html: "Sector indicators capture baseline differences — a megawatt of power plant is not the same as a megawatt of refining capacity." },
    { type: "h2", text: "Reporting regression results" },
    { type: "olist", items: ["State the question and unit of observation (daily, facility, tract).","Report slope, 95% CI, p-value, and R2 with units.","Mention which predictors were included and why.","Show residual plot or note diagnostics.","Use cautious language — associated with, not causes."] },
    { type: "h2", text: "What regression cannot do" },
    { type: "list", items: ["Prove causation without design or strong assumptions.","Fix bad data or missing important predictors.","Extrapolate beyond observed ranges.","Ignore time dependence in sequential data.","Replace domain knowledge — a significant p-value can still be trivial."] },
    { type: "exercise", html: "Fit aqi ~ temp_c on daily LA data. Report slope, p-value, and R2 in plain English. Plot scatter with fitted line. Check residuals vs fitted. Add wind_ms as a second predictor — how does the temperature slope change? Why?", title: "Temperature and AQI", hint: "Use model.summary() and plot. Confounding: wind may explain part of temperature effect.", solution: { lang: "python", code: "import statsmodels.formula.api as smf\nm1 = smf.ols(\"aqi ~ temp_c\", data=aq).fit()\nprint(m1.summary())\nplt.scatter(aq[\"temp_c\"], aq[\"aqi\"], alpha=0.3)\nplt.plot(aq[\"temp_c\"], m1.predict(aq), color=\"red\")\nm2 = smf.ols(\"aqi ~ temp_c + wind_ms\", data=aq).fit()\nprint(\"temp slope alone:\", m1.params[\"temp_c\"])\nprint(\"temp slope + wind:\", m2.params[\"temp_c\"])", note: "If temperature slope shrinks after adding wind, wind explains some co-variation — not necessarily that temperature is unimportant." } },
    { type: "exercise", html: "Using facility data with co2_tons, capacity_mw, and sector: fit log(co2_tons+1) ~ capacity_mw + C(sector). Interpret the capacity coefficient. Plot residuals. Which sector has the highest baseline intercept?", title: "Facility emissions model", hint: "log1p for skew; C(sector) for categories.", solution: { lang: "python", code: "import numpy as np\nfac[\"log_co2\"] = np.log1p(fac[\"co2_tons\"])\nm = smf.ols(\"log_co2 ~ capacity_mw + C(sector)\", data=fac).fit()\nprint(m.summary())\nplt.scatter(m.fittedvalues, m.resid, alpha=0.4)", note: "On log scale, slope approximates percent change in emissions per MW — valid for small coefficients." } },
    { type: "exercise", html: "In R, fit aqi ~ temp_c * season. Plot predicted lines by season using expand.grid and predict. Does temperature matter more in summer than winter?", title: "Seasonal interaction in R", hint: "expand.grid builds prediction grid; interaction term changes slope by season.", solution: { lang: "r", code: "m <- lm(aqi ~ temp_c * season, data = aq)\nsummary(m)\ngrid <- expand.grid(temp_c = seq(15, 40, 1), season = unique(aq$season))\ngrid$pred <- predict(m, newdata = grid)\nlibrary(ggplot2)\nggplot(grid, aes(x = temp_c, y = pred, color = season)) + geom_line()", note: "Different slopes by season suggest chemistry and mixing differ — not just higher summer temperatures." } },
    { type: "h2", text: "Recap" },
    { type: "list", items: ["Regression fits y = intercept + slope*x by least squares.","Read slope (effect size), p-value (evidence), R2 (variance explained), and CI (uncertainty).","Multiple regression isolates each effect holding others constant.","Check residual plots; watch independence with time series.","Say associated with, not causes; do not extrapolate."] },
  ]
};
