module.exports = {
  title: "Time-series analysis",
  track: 'stats', tool: 'Both', level: 'advanced', time: "~5-6 hrs",
  lede: "Climate and environmental data is overwhelmingly time-stamped. Time series have trend, seasonality, and autocorrelation that ordinary methods ignore. This comprehensive lesson covers resampling, smoothing, decomposition, and pitfalls with temperature and AQI examples.",
  learn: [
    "Work with datetime indexes and time slicing",
    "Resample to different frequencies with sensible aggregations",
    "Smooth with rolling windows without look-ahead leakage",
    "Separate trend from seasonality and build anomalies",
    "Recognize autocorrelation and time-series pitfalls"
  ],
  prereqs: [{"id":"pandas","label":"pandas"},{"id":"descriptive-stats","label":"Descriptive statistics"}],
  resources: [
    {
      "name": "pandas time series guide",
      "url": "https://pandas.pydata.org/docs/user_guide/timeseries.html",
      "kind": "docs"
    },
    {
      "name": "Forecasting: Principles & Practice",
      "url": "https://otexts.com/fpp3/",
      "kind": "book"
    },
    {
      "name": "statsmodels: seasonal decompose",
      "url": "https://www.statsmodels.org/stable/generated/statsmodels.tsa.seasonal.seasonal_decompose.html",
      "kind": "docs"
    }
  ],
  unlock: {"label":"Western heat waves","url":"projects.html","blurb":"Decades of daily temperature — resample, smooth, and find the warming trend."},
  content: [
    { type: "p", html: "Climate and environmental data is overwhelmingly time-stamped: hourly AQI, daily temperatures, monthly emissions inventories. Time series have structure — trend, seasonality, autocorrelation — that ordinary methods ignore. This lesson shows how to parse dates, resample, smooth, decompose, and avoid classic pitfalls with Western US temperature and LA air-quality examples." },
    { type: "callout", html: "Treating dated rows as independent samples breaks regression assumptions and inflates confidence. Respect ordering from the start.", variant: "note", title: "Time is not just another column." },
    { type: "h2", text: "Parse dates and set the index" },
    { type: "p", html: "First move: convert date strings to datetime and set them as the index. Sort ascending — out-of-order timestamps cause silent bugs." },
    { type: "code", lang: "python", code: "import pandas as pd\ndf = pd.read_csv(\"western_daily_temp.csv\", parse_dates=[\"date\"])\ndf = df.set_index(\"date\").sort_index()\ndf.head()" },
    { type: "code", lang: "r", code: "library(readr)\nlibrary(lubridate)\ntemp <- read_csv(\"western_daily_temp.csv\") %>%\n  mutate(date = ymd(date)) %>%\n  arrange(date)" },
    { type: "code", lang: "python", code: "df.loc[\"2024-07\"]           # whole month\ndf.loc[\"2020\":\"2023\"]       # year range\ndf.loc[\"2024-06-01\":\"2024-08-31\"]  # summer slice" },
    { type: "h2", text: "Datetime components" },
    { type: "p", html: "Extract year, month, dayofyear for grouping and seasonal analysis." },
    { type: "code", lang: "python", code: "df[\"year\"] = df.index.year\ndf[\"month\"] = df.index.month\ndf[\"doy\"] = df.index.dayofyear" },
    { type: "code", lang: "r", code: "temp <- temp %>%\n  mutate(year = year(date), month = month(date), doy = yday(date))" },
    { type: "h2", text: "Frequency and regular grids" },
    { type: "p", html: "Environmental sensors may miss hours or days. Resample to a regular grid before modelling — daily, monthly, annual — and decide how to fill gaps." },
    { type: "table", head: ["Code","Meaning"], rows: [["\"D\"","Calendar day"],["\"W\"","Week ending"],["\"ME\"","Month end"],["\"QE\"","Quarter end"],["\"YE\"","Year end"]] },
    { type: "h2", text: "Resampling: change the time step" },
    { type: "p", html: "<strong>Resampling</strong> aggregates to a new frequency. Hourly AQI to daily mean; daily temperature to annual max." },
    { type: "code", lang: "python", code: "hourly = pd.read_csv(\"la_aqi_hourly.csv\", parse_dates=[\"timestamp\"])\nhourly = hourly.set_index(\"timestamp\").sort_index()\ndaily_aqi = hourly[\"aqi\"].resample(\"D\").mean()\nmonthly_max = hourly[\"aqi\"].resample(\"ME\").max()\nyearly_mean = df[\"tmax_c\"].resample(\"YE\").mean()" },
    { type: "code", lang: "r", code: "library(xts)\nlibrary(dplyr)\ndaily <- temp %>%\n  group_by(date = floor_date(date, \"day\")) %>%\n  summarise(tmax_c = max(tmax_c, na.rm = TRUE))" },
    { type: "callout", html: "Heat-wave detection needs daily data. Long-term warming trends often use annual means. Do not over-aggregate before you have explored daily structure.", variant: "tip", title: "Pick frequency to match the question." },
    { type: "h2", text: "Aggregation choices" },
    { type: "list", items: ["<strong>mean:</strong> typical value over the period — daily mean AQI.","<strong>max:</strong> worst case — daily peak AQI or annual hottest day.","<strong>sum:</strong> totals — monthly rainfall accumulation.","<strong>median:</strong> robust centre for skewed hourly data."] },
    { type: "code", lang: "python", code: "daily = hourly[\"aqi\"].resample(\"D\").agg([\"mean\", \"max\", \"median\", \"count\"])" },
    { type: "h2", text: "Rolling windows and smoothing" },
    { type: "p", html: "Raw series are noisy. A <strong>rolling mean</strong> averages each point with neighbours to reveal underlying movement." },
    { type: "code", lang: "python", code: "daily_t = df[\"tmax_c\"]\nroll_7 = daily_t.rolling(window=7, center=True).mean()\nroll_30 = daily_t.rolling(window=30, center=True).mean()\nax = daily_t.plot(alpha=0.3, figsize=(10,4), label=\"daily\")\nroll_30.plot(ax=ax, color=\"crimson\", label=\"30-day avg\")\nax.legend()" },
    { type: "callout", html: "Wider windows are smoother but lag more and hide short events. Narrow windows track closely but stay noisy. Match window to the pattern scale you care about.", variant: "note", title: "Window size trade-off." },
    { type: "h2", text: "Centered vs trailing windows" },
    { type: "p", html: "center=True uses past and future neighbours — fine for exploration, forbidden for forecasting. For prediction, use trailing windows only." },
    { type: "code", lang: "python", code: "trailing = daily_t.rolling(window=7, center=False).mean()  # safe for forecasts" },
    { type: "callout", html: "A centred rolling mean at time t uses future values. Never put centred smoothers into features for forward prediction.", variant: "warn", title: "Look-ahead leakage." },
    { type: "h2", text: "Shifting and lag features" },
    { type: "p", html: "Yesterday's AQI predicts today's. Create lags with shift() — positive shift pulls past values forward." },
    { type: "code", lang: "python", code: "daily_aqi_lag = daily_aqi.to_frame(\"aqi\")\ndaily_aqi_lag[\"lag1\"] = daily_aqi_lag[\"aqi\"].shift(1)\ndaily_aqi_lag[\"lag7\"] = daily_aqi_lag[\"aqi\"].shift(7)" },
    { type: "h2", text: "Trend vs seasonality vs noise" },
    { type: "p", html: "Most environmental series combine a long-run <strong>trend</strong>, repeating <strong>seasonal</strong> cycle, and <strong>noise</strong>. Decomposition separates them." },
    { type: "code", lang: "python", code: "monthly = df[\"tmax_c\"].resample(\"ME\").mean()\nfrom statsmodels.tsa.seasonal import seasonal_decompose\nresult = seasonal_decompose(monthly.dropna(), model=\"additive\", period=12)\nresult.plot()" },
    { type: "p", html: "Additive model: observed = trend + seasonal + residual. Multiplicative when seasonal amplitude grows with level — common for emissions." },
    { type: "code", lang: "python", code: "result_mul = seasonal_decompose(monthly.dropna(), model=\"multiplicative\", period=12)" },
    { type: "h2", text: "Detrending and anomalies" },
    { type: "p", html: "A <strong>climatology</strong> is the long-term average for each calendar month or day. <strong>Anomaly</strong> = value minus climatology — removes seasonal cycle so trends stand out." },
    { type: "code", lang: "python", code: "monthly_anom = monthly - monthly.groupby(monthly.index.month).transform(\"mean\")\nmonthly_anom.plot(title=\"Temperature anomaly vs monthly climatology\")" },
    { type: "callout", html: "Western heat-wave projects use anomalies to ask: how far above normal was this summer?", variant: "tip", title: "Anomalies are the climate staple." },
    { type: "h2", text: "Autocorrelation" },
    { type: "p", html: "Today's temperature correlates with yesterday's — <strong>autocorrelation</strong>. High autocorrelation means points are not independent; regression p-values get over-confident." },
    { type: "code", lang: "python", code: "from statsmodels.graphics.tsaplots import plot_acf\nplot_acf(daily_t.dropna(), lags=40)" },
    { type: "p", html: "ACF plot shows correlation at lag 1, 2, 3 days. Slow decay indicates strong persistence — heat spells linger." },
    { type: "callout", html: "Random train/test splits leak the future into the past. Always split chronologically for forecasting.", variant: "warn", title: "Do not shuffle time series." },
    { type: "h2", text: "Spurious correlation" },
    { type: "p", html: "Two series both trending upward — CO2 and smartphone sales — correlate strongly while unrelated. Detrend or use anomalies before correlating." },
    { type: "code", lang: "python", code: "spurious = daily_aqi.corr(daily_t)  # may reflect shared seasonality\n# better: correlate anomalies or deseasonalised series" },
    { type: "h2", text: "Time zones and daylight saving" },
    { type: "p", html: "Hourly environmental data hits timezone and DST bugs. Store UTC or document local timezone. Pandas tz_localize and tz_convert handle conversions." },
    { type: "code", lang: "python", code: "hourly.index = hourly.index.tz_localize(\"America/Los_Angeles\", ambiguous=\"NaT\")" },
    { type: "callout", html: "DST fall-back repeats an hour — ambiguous=\"NaT\" flags it instead of guessing wrong.", variant: "warn", title: "Ambiguous hours." },
    { type: "h2", text: "Gaps and interpolation" },
    { type: "p", html: "Sensors fail. Small gaps might be interpolated; large gaps should stay missing. Never interpolate across months without thought." },
    { type: "code", lang: "python", code: "daily_filled = daily_t.interpolate(method=\"time\", limit=3)  # max 3-day gap" },
    { type: "list", items: ["<strong>Forward fill:</strong> carry last value — OK for slow-changing state.","<strong>Linear interpolate:</strong> straight line between points — OK for short gaps.","<strong>Leave NaN:</strong> safest default for analysis."] },
    { type: "h2", text: "Hourly AQI patterns" },
    { type: "h3", text: "Diurnal cycle" },
    { type: "p", html: "Pollution often peaks morning and evening rush hours. Group by hour-of-day to see the diurnal fingerprint." },
    { type: "code", lang: "python", code: "hourly[\"hour\"] = hourly.index.hour\ndiurnal = hourly.groupby(\"hour\")[\"aqi\"].median()\ndiurnal.plot(kind=\"bar\")" },
    { type: "h3", text: "Day-of-week effects" },
    { type: "code", lang: "python", code: "hourly[\"dow\"] = hourly.index.dayofweek\nhourly.boxplot(column=\"aqi\", by=\"dow\")" },
    { type: "h2", text: "Annual warming trend" },
    { type: "p", html: "Resample daily temperature to annual mean, plot with rolling decade average. Is the West warming beyond year-to-year noise?" },
    { type: "code", lang: "python", code: "annual = df[\"tmax_c\"].resample(\"YE\").mean()\ndecade = annual.rolling(window=10, center=True).mean()\nax = annual.plot(label=\"annual mean\", alpha=0.6)\ndecade.plot(ax=ax, color=\"darkred\", linewidth=2, label=\"10-yr rolling\")\nax.legend()" },
    { type: "code", lang: "r", code: "annual <- temp %>%\n  group_by(year) %>%\n  summarise(tmax = mean(tmax_c, na.rm = TRUE))\nggplot(annual, aes(x = year, y = tmax)) + geom_line() + geom_smooth(method = \"loess\")" },
    { type: "h2", text: "Change-point thinking" },
    { type: "p", html: "Trends need not be linear. A step change after a policy or fire season is a different story than gradual warming. Plot first; do not force one line through everything." },
    { type: "callout", html: "A sudden AQI drop might be a new filter rule, not weather. Annotate plots with known events when you can.", variant: "note", title: "Policy and events." },
    { type: "h2", text: "Simple forecasting preview" },
    { type: "p", html: "Chronological split: train on early years, test on recent years. Compare persistence forecast (tomorrow = today) to rolling mean baseline." },
    { type: "code", lang: "python", code: "train = daily_t[\"2010\":\"2019\"]\ntest = daily_t[\"2020\":\"2024\"]\npersist = test.shift(1)  # naive: yesterday predicts today\nrmse = ((test - persist) ** 2).mean() ** 0.5\nprint(\"persistence RMSE:\", rmse)" },
    { type: "p", html: "Full forecasting is its own field — this lesson equips you to prepare series correctly before reaching for ARIMA or Prophet." },
    { type: "h2", text: "Merging time series" },
    { type: "p", html: "Join daily AQI with daily weather on the date index. Use inner join to keep overlapping dates only." },
    { type: "h2", text: "Reporting time-series findings" },
    { type: "steps", items: ["State time range, frequency, and timezone.","Plot raw and smoothed series on the same axes.","Separate trend from seasonality when claiming warming or improvement.","Report autocorrelation awareness if using regression.","Split chronologically for any predictive claim."] },
    { type: "exercise", html: "From a multi-decade daily tmax_c series: set datetime index, compute annual means, overlay a 10-year rolling average, decompose monthly data into trend and seasonality. Is there warming beyond the seasonal cycle? Quantify the change in annual mean between first and last decade.", title: "Find the warming signal", hint: "resample(\"YE\").mean() for annual; seasonal_decompose(..., period=12) on monthly.", solution: { lang: "python", code: "df = pd.read_csv(\"western_daily_temp.csv\", parse_dates=[\"date\"]).set_index(\"date\").sort_index()\nannual = df[\"tmax_c\"].resample(\"YE\").mean()\nannual.rolling(10, center=True).mean().plot()\nmonthly = df[\"tmax_c\"].resample(\"ME\").mean()\nfrom statsmodels.tsa.seasonal import seasonal_decompose\nseasonal_decompose(monthly.dropna(), period=12).plot()\nprint(\"first decade mean:\", annual[\"1980\":\"1989\"].mean())\nprint(\"last decade mean:\", annual[\"2015\":\"2024\"].mean())", note: "Trend panel should rise if warming is present; compare decades for a simple numeric summary." } },
    { type: "exercise", html: "Using hourly LA AQI: resample to daily max, compute monthly median AQI, count fraction of days with max AQI >= 100 per year, plot both. Which month has worst typical air? Is the bad-day rate increasing?", title: "AQI seasonality and bad-day rate", hint: "resample(\"D\").max() then groupby month or year.", solution: { lang: "python", code: "h = pd.read_csv(\"la_aqi_hourly.csv\", parse_dates=[\"timestamp\"]).set_index(\"timestamp\")\ndaily_max = h[\"aqi\"].resample(\"D\").max()\nmonthly_med = daily_max.resample(\"ME\").median()\nbad = (daily_max >= 100).astype(int)\nby_year = bad.resample(\"YE\").mean()\nmonthly_med.plot(title=\"Monthly median of daily max AQI\")\nby_year.plot(title=\"Fraction of bad days per year\")", note: "Daily max captures worst-hour exposure; fraction bad days is an actionable public-health summary." } },
    { type: "exercise", html: "In R, load daily temperature, compute ACF for up to 30 lags, fit lm(tmax_c ~ year(doy)) on day-of-year — note inflated significance. Compare to lm on annual means instead.", title: "Autocorrelation check in R", hint: "acf() for autocorrelation; aggregate before regression for trend.", solution: { lang: "r", code: "library(lubridate)\ntemp <- read_csv(\"western_daily_temp.csv\") %>% mutate(date = ymd(date))\nacf(temp$tmax_c, lag.max = 30)\nm_daily <- lm(tmax_c ~ yday(date), data = temp)\nsummary(m_daily)\nannual <- temp %>% group_by(year = year(date)) %>% summarise(tmax = mean(tmax_c))\nm_annual <- lm(tmax ~ year, data = annual)\nsummary(m_annual)", note: "Daily regression p-values are optimistic when residuals autocorrelate; annual aggregation reduces dependence." } },
    { type: "h2", text: "Recap" },
    { type: "list", items: ["Parse dates, sort, and set a datetime index first.","resample() changes frequency; rolling() smooths noise — mind center=False for forecasting.","Decompose into trend + seasonality + residual; anomalies remove seasonal cycle.","Respect autocorrelation; avoid leakage and random splits.","Document timezone, gaps, and aggregation choices in every report."] },
  ]
};
